### ISSUE TITLE
Uncaught TypeError: _this.compilerMessages.push is not a function

### ISSUE THREAD

**Issue by ezickler** [grz0zrg/tools-povray#3] opened 2016-11-30 10:43 UTC
It renders but i get the following error.

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: "Fedora release
**Thrown From**: [tools-povray](https://github.com/grz0zrg/tools-povray) package, v1.0.2

### Stack Trace

Uncaught TypeError: _this.compilerMessages.push is not a function

```
At ~/.atom/packages/tools-povray/lib/init.coffee:192

TypeError: _this.compilerMessages.push is not a function
    at ~/.atom/packages/tools-povray/lib/init.coffee:192:31
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:87:13)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -2:46.7.0 application:open-file (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:39.1.0 core:save (input#tools-povray.povrayPreview.)
     -1:37.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:35.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:35.2.0 povray:parse (atom-text-editor.editor)
     -1:21.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:21.9.0 povray:parse (atom-text-editor.editor.is-focused)
     -1:20.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:20.2.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -1:16.8.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:15.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:15.3.0 povray:parse (atom-text-editor.editor.is-focused)
     -0:09.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:09.9.0 povray:parse (atom-text-editor.editor.is-focused)
     -0:03.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:03.9.0 povray:parse (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "platformio-ide",
      "platformio-ide-terminal",
      "linter-chktex"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".pioenvs",
      ".piolibdeps",
      ".clang_complete",
      ".gcc-flags.json"
    ],
    "telemetryConsent": "limited"
  },
  "tools-povray": {}
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.6 (active)
atom-beautify, v0.29.13 (active)
atom-language-povray, v0.1.1 (active)
autocomplete-clang, v0.10.0 (active)
build, v0.67.0 (active)
build-cargo, v1.0.0 (active)
busy, v0.7.0 (active)
dash, v1.7.0 (inactive)
language-ini, v1.16.0 (active)
language-latex, v1.0.0 (active)
language-rust, v0.4.8 (active)
latex, v0.41.0 (inactive)
linter, v1.11.18 (active)
linter-chktex, v1.3.0 (inactive)
linter-cpplint, v1.0.1 (active)
linter-gcc, v0.6.15 (active)
pdf-view, v0.53.0 (active)
platformio-ide, v1.6.0 (inactive)
platformio-ide-terminal, v2.2.2 (inactive)
project-manager, v3.3.3 (active)
tool-bar, v1.0.1 (active)
tools-povray, v1.0.2 (active)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by grz0zrg** [comment] 2016-12-24 02:08
Sorry for the late reply, did not see it for some reasons.

The issue is known and is due to a missing function (unfold) in the "atom-message-panel" package because it was modified to add that function, the modified version is bundled here so to fix this error you basically have to replace the "atom-message-panel" folder in "~/.atom/packages/tools-povray/node_modules/" to the one that is bundled here.

This is a temporary fix because i don't know right now how i can force atom to use the bundled dependency instead of the official one, if someone know, please tell me :)

As soon as my "atom-message-panel" unfold addition will be tagged, it will work, right now the commit has been officially accepted so it will appear in the next version of "atom-message-panel"!

**Comment by grz0zrg** [comment] 2017-04-01 14:54
This is now fixed with the latest update of "atom-message-panel".

**Closed as completed by grz0zrg** 2017-04-01 14:54 UTC
Labels: bug
